### PR TITLE
Fix: Safari Keyboard open/close viewport height update

### LINKED ISSUE #2430: Dimensions change event is not fired on iOS (Safari)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Dimensions `change` event is not fired when keyboard is triggered on Safari.

It's similar to this issue #1369 which we have fixed in the past.

### Expected behavior

The event should be fired when keyboard state changes, like it does on Chrome.

CSB Preview: https://scdqh6.sse.codesandbox.io/dimensions

### Steps to reproduce

1. Go to above CSB Preview URL
2. Interact with the text input.
3. See the `window.height` does not change

### Test case

https://codesandbox.io/s/stupefied-brook-scdqh6?file=/pages/dimensions/index.js

### Additional comments

_No response_

### PR DESCRIPTION
**Pull request by rawalyogendra**
Fixes: https://github.com/necolas/react-native-web/issues/2430

## Details
This PR fixes the issue we have on iOS, which does not fire Viewport `resize` when keyboard opens/close on mWeb.

The PR is pending in Upstream repo, so I am adding my changes here as advised https://github.com/Expensify/App/issues/11463#issuecomment-1360815468

As we are behind the Upstream repo, I have updated my code to match our fork's version.

I have not added the test as it is still being reviewed by the Upstream repo owner. 

https://user-images.githubusercontent.com/7548730/208975170-390e431e-9fea-49dc-9b4e-38c8c413f10d.mp4

### CODE REVIEW

**Comment by youssef-lr** [comment]
Could you add the test you added to the upstream repo in this PR as well?

**Comment by youssef-lr** [comment]
Changes LGTM, however when testing the changes in App, there's a delay until the button shows up. See the recording below and a comparison to how it works in native:

https://user-images.githubusercontent.com/9680864/209029498-abab54ab-d19c-4d91-b815-e7d50710178f.mov

But I think this can be worked on in App, would you be able to look into this afterwards? Just double checking here before merging in case this is something that can be fixed here.

**Comment by rawalyogendra** [comment]
@youssef-lr I am aware about the issue but there is nothing we can do here as iOS only updates the height after rhe keyboard animation is completed.

https://github.com/Expensify/App/issues/11463#issuecomment-1337979872

It was discussed in the original issue thread as well.

File: packages/react-native-web/src/exports/Dimensions/index.js [hunk 1]
```diff
@@ -77,13 +77,24 @@ export default class Dimensions {
     }
 
     const win = window;
-    const docEl = win.document.documentElement;
+    let height;
+    let width;
+
+    if (win.visualViewport) {
```
Comment (flodnv) [inline packages/react-native-web/src/exports/Dimensions/index.js:89]: Is this the same as "if safari mweb"?

Comment (flodnv) [reply packages/react-native-web/src/exports/Dimensions/index.js:89]: Maybe we should add a comment briefly explaining this if/else?

**Review by mountiny — DISMISSED** [review]
@rawalyogendra Looks good to me, I think the Safari lag is something we might have to swallow for now with how the animation works.

File: packages/react-native-web/src/exports/Dimensions/index.js (hunk 1 above)
Comment (kidroca) [reply packages/react-native-web/src/exports/Dimensions/index.js:89]: > Is this the same as "if safari mweb"?

I think it's a feature check, but according to caniuse all live browsers support the `visualViewport`: https://caniuse.com/?search=visualViewport

Since react-native-web also dropped support for IE11, I don't think we need to check `if (win.visualViewport)` - it will always be `true` 

--- 

Same for the other case that assigns the listener

**Review by kidroca — COMMENTED** [review]
This PR looks good to me

I have a NAB comment about the feature check made here: https://github.com/Expensify/react-native-web/pull/10/files#r1069553372

@rawalyogendra Can you confirm this change would preserve the original behavior if a web page is rendered inside an iframe?

File: packages/react-native-web/src/exports/Dimensions/index.js (hunk 1 above)
Comment (marcaaron) [reply packages/react-native-web/src/exports/Dimensions/index.js:89]: Agree it would be good to add a comment. Also not sure about support IE I agree with @kidroca and don't think it matters.

Comment (marcaaron) [reply packages/react-native-web/src/exports/Dimensions/index.js:89]: Oh actually if the maintainer is asking for it here then I'd say we just roll with this: https://github.com/necolas/react-native-web/pull/2438#issuecomment-1325575727

**Review by marcaaron — DISMISSED** [review]

**Review by mananjadhav — DISMISSED** [review]

File: packages/react-native-web/src/exports/Dimensions/index.js (hunk 1 above)
Comment (rawalyogendra) [reply packages/react-native-web/src/exports/Dimensions/index.js:89]: @marcaaron is correct. The feature check is not required as all modern browsers support VisualViewport which is evident from the above caniuse.com link.

But the original repo maintainer requested that check so I had to add it.

**Comment by mananjadhav** [comment]
The changes look fine to me, and ya we only had `win.visualViewport` earlier but after maintainer's request we retained the else part.

> preserve the original behavior if a web page

@kidroca If I understand your question correctly, I think it shouldn't break the original behavior for [iframe](https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport). 

```
For an <iframe>, visual viewport metrics like `VisualViewport.width` always correspond to layout viewport metrics like `document.documentElement.clientWidth`
```

**Comment by rawalyogendra** [comment]
@kidroca I will have to test if the original behavior is preserved when the page is rendered in an iframe.

I will update here when I test it out.

File: packages/react-native-web/src/exports/Dimensions/index.js (hunk 1 above)
Comment (flodnv) [reply packages/react-native-web/src/exports/Dimensions/index.js:89]: Can we add a comment summarizing all this please?

**Comment by flodnv** [comment]
>@kidroca I will have to test if the original behavior is preserved when the page is rendered in an iframe.
>I will update here when I test it out.


Ok thanks @rawalyogendra let us know

File: packages/react-native-web/src/exports/Dimensions/index.js (hunk 1 above)
Comment (rawalyogendra) [reply packages/react-native-web/src/exports/Dimensions/index.js:89]: I will add a comment summarizing of my changs today. Sorry for the delay.

**Comment by rawalyogendra** [comment]
@flodnv I will update you guys today

**Comment by flodnv** [comment]
Thanks @rawalyogendra, looking forward to it!

File: packages/react-native-web/src/exports/Dimensions/index.js [hunk 2]
```diff
@@ -77,13 +77,31 @@ export default class Dimensions {
...
-    const docEl = win.document.documentElement;
+    let height;
+    let width;
+
+    /*
+     * iOS does not update viewport dimensions on keyboard open/close
+     * So, we are using window.visualViewport(https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport)
+     * instead of document.documentElement.clientHeight
+     * But we are still using document.documentElement.clientWidth as fallback
+     * because it was requested by the original repo owner
```
Comment (mountiny) [inline packages/react-native-web/src/exports/Dimensions/index.js]: NAB: I think its fine to be kept like this
```suggestion
     * document.documentElement.clientWidth is used as a fallback
```

File: packages/react-native-web/src/exports/Dimensions/index.js [hunk 3]
```diff
@@ -125,5 +143,13 @@ export default class Dimensions {
 }
 
 if (canUseDOM) {
-  window.addEventListener('resize', Dimensions._update, false);
+  /*
+   * Same here as in _update method
+   * keeping the previous implementation as fallback
```
Comment (mountiny) [inline packages/react-native-web/src/exports/Dimensions/index.js]:
```suggestion
   * Same as in _update method, we are
   * keeping the previous implementation as a fallback
```

**Review by mountiny — DISMISSED** [review]
@rawalyogendra Thank you! Left two suggestions to the comments!

**Comment by rawalyogendra** [comment]
@flodnv I have added comments as requested.

And I have also tested this change on a webpage rendered inside an iframe, albeit in a quick and dirty way. 

It works on Android

https://user-images.githubusercontent.com/7548730/212980363-7bac1a44-2677-44bc-a65b-9e4d557e2d82.mp4

But does not work on Safari

https://user-images.githubusercontent.com/7548730/212983996-7f1fa471-198f-4cff-b7c0-d5944022a56f.mp4

If you look at the Android video, you'll see that the entire webpage's height is adjusting dynamically, along with the iFrame's height. This results in the text at the bottom moving smoothly with the keyboard as well as the height being updated. However, this behavior is not present on iOS. 

If you would like me to investigate further, I am happy to do so. However, I want to caution that this may be uncharted territory, so there may not be a clear resolution to the issue.

cc: @kidroca @mountiny @marcaaron

**Review by marcaaron — APPROVED** [review]
Looks good to me. I think we should do the checklist for this one? Or do we do that when we update the fork I'm not sure?

**Review by mananjadhav — APPROVED** [review]

**Comment by flodnv** [comment]
@marcaaron which checklist? The PR Reviewer checklist? I think we can do that in the App PR

**Review by flodnv — APPROVED** [review]

**Comment by flodnv** [comment]
Thanks @rawalyogendra! Go ahead and submit the corresponding App PR 🙇

**Comment by rawalyogendra** [comment]
@flodnv on it

**Comment by marcaaron** [comment]
>@marcaaron which checklist? The PR Reviewer checklist? I think we can do that in the App PR

Yes. We can. Mainly brought this up as there are many things in the checklist that can apply to the current PR. Maybe not so much the testing on all platforms, but a lot of the items touch on code quality standards etc.
